spring:
  profiles:
    include:
      - core

  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET_NAME}
        credentials:
          accessKey: ${AWS_ACCESS_KEY}
          secretKey: ${AWS_SECRET_KEY}
        region:
          static: ${AWS_STATIC}
        stack:
          auto: false
        base:
          url: ${AWS_BASE_URL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${NAVER_EMAIL}
    password: ${NAVER_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${MAIL_HOST}
            protocols: TLSv1.2

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  port: ${USER_PORT}

toss:
  clientKey: ${TOSS_CLIENT_KEY}
  secretKey: ${TOSS_SECRET_KEY}