spring:
  profiles:
    include:
      - core

  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET_NAME}
        credentials:
          accessKey: ${AWS_ACCESS_KEY}
          secretKey: ${AWS_SECRET_KEY}
        region:
          static: ${AWS_STATIC}
        stack:
          auto: false
        base:
          url: ${AWS_BASE_URL}

server:
  port: 8080

toss:
  clientKey: ${TOSS_CLIENT_KEY}
  secretKey: ${TOSS_SECRET_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}