spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DB_URL}/sycls
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  #    더미 데이터 셋
  sql:
    init:
      encoding: UTF-8
      mode: always

---
spring:
  config:
    activate:
      on-profile: dev