spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://${DB_URL}/sycls
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET_NAME}
        credentials:
          accessKey: ${AWS_ACCESS_KEY}
          secretKey: ${AWS_SECRET_KEY}
        region:
          static: ${AWS_STATIC}
        stack:
          auto: false
        base:
          url: ${AWS_BASE_URL}
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
logging:
  level:
    com.b1: DEBUG

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DEV_DB_URL}/${DEV_DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    aws:
      s3:
        bucket: ${AWS_BUCKET_NAME}
        credentials:
          accessKey: ${AWS_ACCESS_KEY}
          secretKey: ${AWS_SECRET_KEY}
        region:
          static: ${AWS_STATIC}
        stack:
          auto: false
        base:
          url: ${AWS_BASE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}
