###

@categoryId = 4

### 카테고리 등록
POST http://localhost:8081/v1/categories
Authorization: {{Authorization}}
Content-Type: application/json

{
  "name": "아이유콘서트"
}

### 카테고리 수정
PATCH http://localhost:8081/v1/categories/{{categoryId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "name": "테스트카테고리"
}


### 카테고리 삭제
DELETE http://localhost:8081/v1/categories/{{categoryId}}
Authorization: {{Authorization}}


### 카테고리 복구
PATCH http://localhost:8081/v1/categories/{{categoryId}}/reactivate
Authorization: {{Authorization}}


### 카테고리 조회 (어드민)
GET http://localhost:8081/v1/categories
Authorization: {{Authorization}}