
@contentId = 9

### 공연수정
PATCH http://localhost:8081/v1/contents/{{contentId}}
Content-Type: multipart/form-data
#Content-Type: application/json

{
  "categoryId": 1,
  "title": "공연 제목 수정",
  "description": "소개 수정",
  "oldMainImagePath": "https://sycls-test.s3.ap-northeast-2.amazonaws.com/content/main/f8f9b91d-fdde-4205-af54-2c58f5419d60jpg",
  "detailImagePaths": [
    "https://sycls-test.s3.ap-northeast-2.amazonaws.com/content/detail/038b08e4-9f6f-40c3-8c31-0559958f43fcjpg",
    "https://sycls-test.s3.ap-northeast-2.amazonaws.com/content/detail/ca740863-ddb4-42b9-a0b0-ec1b349da576jpg"
  ]
}
