@contentId = 8

### 공연 상태 수정
PATCH http://localhost:8081/v1/contents/{{contentId}}/status
Authorization: {{Authorization}}
Content-Type: application/json

{
  "status": "VISIBLE"
}

### 공연 단일 조회
GET http://localhost:8081/v1/contents/{{contentId}}
Authorization: {{Authorization}}

### 공연 전체 조회
GET http://localhost:8081/v1/contents