@roundId = 1

### 회차 등록
POST http://localhost:8081/v1/rounds
Content-Type: application/json

{
  "contentId": 1,
  "placeId": 1,
  "sequence": 1,
  "status": "WAITING",
  "startDate": "2024-09-05",
  "startTime": "05:00",
  "endTime": "06:00"
}


### 회차 상태 수정
PATCH http://localhost:8081/v1/rounds/{{roundId}}/status
Content-Type: application/json

{
  "status": "WAITING"
}

### 회차 정보 수정
PATCH http://localhost:8081/v1/rounds/2
Content-Type: application/json

{
  "startDate": "2024-09-05",
  "startTime": "04:00",
  "endTime": "05:00"
}

### 회차 단일 조회
GET localhost:8081/v1/rounds/{{roundId}}