### POST 좌석-등급 등록
POST http://localhost:8081/v1/seat-grades
Content-Type: application/json

{
  "contentId": 1,
  "roundId": 1,
  "seatGradeType": "VIP",
  "seatIdList": [
    1,
    2
  ],
  "price": 10000
}



### GET 좌석-등급 설정 확인
GET http://localhost:8081/v1/seat-grades/confirm?roundId=1



### GET 좌석-등급 전체 조회
GET http://localhost:8081/v1/seat-grades?roundId=1



### PATCH 좌석-등급 수정
PATCH http://localhost:8081/v1/seat-grades
Content-Type: application/json

{
  "seatGradeIdList": [
    1
  ],
  "seatGradeType": "A",
  "price": 1000
}


### DELETE 좌석-등급 삭제
DELETE http://localhost:8081/v1/seat-grades
Content-Type: application/json

{
  "seatGradeIdList": [
    2
  ]
}
